import os
import sys
import re
from github import Github, Auth

if len(sys.argv) < 3:
    print("Usage: python update_status.py <DEV|UAT|PROD> '<STATUS_TEXT>'")
    sys.exit(1)

env_name = sys.argv[1].upper()
status_text = sys.argv[2]

token = os.getenv("GITHUB_TOKEN")
repo_name = os.getenv("GITHUB_REPOSITORY")
commit_sha = os.getenv("GITHUB_SHA")

if not token or not repo_name or not commit_sha:
    print("Error: Missing required environment variables (GITHUB_TOKEN, GITHUB_REPOSITORY, GITHUB_SHA).")
    sys.exit(1)

auth = Auth.Token(token)
g = Github(auth=auth)
repo = g.get_repo(repo_name)

commit = repo.get_commit(commit_sha)
pulls = list(commit.get_pulls())

if not pulls:
    print(f"No Pull Requests associated with commit {commit_sha} were found.")
    sys.exit(0)

for pr in pulls:
    print(f"Updating status in PR #{pr.number} -> {env_name}: {status_text}")
    comments = pr.get_issue_comments()
    target_comment = None
    
    # Search for the comment generated by dbt Slim CI
    for comment in comments:
        if "dbt Slim CI" in comment.body:
            target_comment = comment
            break
            
    if target_comment:
        body = target_comment.body
        
        # Initialize the Deployment Status section if it doesn't exist yet
        if "### 🚀 Deployment Status" not in body:
            body += "\n\n---\n### 🚀 Deployment Status\n* **DEV:** ⏳ Pending\n* **UAT:** ⏳ Pending\n* **PROD:** ⏳ Pending"
        
        # Replace the specific environment line using regex for flexibility
        pattern = rf"\* \*\*{env_name}:\*\* .*"
        replacement = f"* **{env_name}:** {status_text}"
        
        if re.search(pattern, body):
            body = re.sub(pattern, replacement, body)
        else:
            body += f"\n* **{env_name}:** {status_text}"
            
        target_comment.edit(body)
        print(f"{env_name} status updated successfully in PR #{pr.number}.")
    else:
        print(f"No 'dbt Slim CI' comment was found in PR #{pr.number}.")